# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ai3ocwYTTay4mHge1QDzmHDUlEJyaMgi
"""

#making trie 

def make_trie(*words):
    root = {}
    if len(words) == 0:
        return "Please enter a name"
    for word in words:
        if not word: 
            continue
        current_dict = root 
        for letter in word:
            if letter not in current_dict:
                current_dict[letter] = {}
            current_dict = current_dict[letter]
        if letter == word[-1]:
            current_dict["Flag"] = True 
    return root
    
make_trie()

#deletion


def delete_from_trie(word):
    current_dict = trie
    stack = [(current_dict, word)]
    for letter in word:
        if letter not in current_dict:
            return "The word is not present in the trie"
        stack.append((current_dict, letter))
        current_dict = current_dict[letter]
    if "Flag" not in current_dict:
        return "The word is not present in the trie"
    del current_dict["Flag"]
    if not current_dict:
        while stack:
            current_dict, letter = stack.pop()
            del current_dict[letter]  #is line ki wajah se error araha hai jab sab ur gaya  na toh error dega shafique wale iteration mein jaa
            if current_dict:
                break
    return "The word has been successfully deleted from the trie"

delete_from_trie("Shaaf")
delete_from_trie("Shafique")

# searching in trie using dfs


def search_trie(root,word):
    if len(root) == 0 or len(word) == 0:
        return "False arguements"
    for letter in word:
        if letter in root:
            root = root[letter]
        else:
            return False
    
    if True in root:
        return ("Item found",word)
    
    # for child in root.values():
    #     if dfs_root(child, ''):
    #         return True
    
    return False

print(search_trie(root,"Shaaf"))